### ISSUE TITLE
when edit a comment add/edit an url the bot is not triggered.

### ISSUE THREAD

**Issue by Raffaello** [probot/unfurl#50]
for eg create a comment

than edit adding a url

the bot is not triggered.

the same should apply:
create a comment with url, work as expected,
then edit the comment change to another url, the bot is not triggerd.

**Comment by jizusun** [comment]
I guess it's designed for simplicity, because as far as I tried,

To create a comment in an issue will trigger 
```
 "event": "issue_comment.created",
```
and then the bot would update this issue, which will trigger
```
 "event": "issue_comment.edited",
```


But in the entrypoint, only `created` event are taken cared of 

https://github.com/probot/unfurl/blob/81e04d68d7eafce7475ec6081a7b55ac5de2544b/lib/index.js#L4-L21
